### ISSUE TITLE
The analyze mode should not care about comments

### ISSUE THREAD

**Issue by sorawee** [jackfirth/resyntax#232]
Users of the analyze mode are already applying the changes manually, so it's fine to strip comments away. This is especially good if doing so allows Resyntax to discover more issues.

**Comment by jackfirth** [comment]
I've greatly improved Resyntax's ability to preserve comments automatically (see #247 and #243). There's still some gaps, but I believe most situations are fixable now. I've also added debug logging, which records when a suggestion is discarded due to dropped comments. Given all that, I will close this for now, as it should be unnecessary.
