### ISSUE TITLE
Proving the safety of rules (and maybe other properties)

### ISSUE THREAD

**Issue by Metaxal** [jackfirth/resyntax#29]
@jackfirth asked this recently:
> Is this code:
```racket
(let ([v <expr>])
  (or (and v <expr-not-returning-false-or-referencing-v>)
      <expr-not-referencing-v>))
```
> Equivalent to this:
```racket
(if <expr>
    <expr-not-returning-false-or-referencing-v>
    <expr-not-referencing-v>)
```

This case is simple enough that it should be amenable to an almost-formal proof of some guarantees. How can we be mechanically (almost) certain that the two codes are equivalent, for some definition of equivalence?

A related case, maybe simpler:
```racket
(or (not x:expr) (not y:expr) ...)
; -->
(and x y ...)
```
These are 'logically' equivalent (De Morgan's law), but are there may be more dimensions to consider, in particular since Racket's `or` and `not` don't behave exactly like their logical counterparts (e.g., the order matters).

The question is: 'What are the mechanisms about Racket (expander, compiler, GC, etc.) that one needs to deal with to prove some of the following properties:
* logical equivalence: don't care about time and memory resources, temporary mutation, etc. as long as the program produces the same result
* logical subsumption: the program is logically equivalent in all situation that don't raise an exception
* preserving (or not) (the lack of) tail calls
* preserving (or not) (the lack of) compiler optimizations
* readability (e.g., preserving comments, variable names, not introducing new variables, etc.)
* [to be completed]

Some things to consider (but maybe not all of them at the same time):
* observing continuation marks may prevent performing tail call optimisations
* side effects (although mutating a local variable can sometimes be allowed)
* preserving failure behaviour (performing a transformation that makes the code 'more correct' may not be desirable). For example turning `(let ([v <expr>]) v)` into `<expr>` may prevent failure if `<expr>` returns multiple values (h/t shu--hung)
* global control flow such as continuations
* ...?

Then next to each rule we could have a set of guarantees that hold, and those that may not hold.

**Comment by jackfirth** [comment]
The high-level goal in terms of rule safety is "safe enough that users can run the tool across a large codebase without reviewing _every_ changed line." Which of those listed properties correspond to that goal is an open question. Here's my thoughts so far:

1. We can't assume expressions can be reordered safely. Racket isn't Haskell, side effects are used in real code. Rules should probably avoid changing the evaluation order of expressions.
2. Preserving compiler optimizations probably isn't necessary. Rules are intended to produce more readable code: if an optimization isn't firing on readable code but is firing on unreadable code, I think we should investigate whether that optimization can be improved rather than giving users good motivation to write unreadable code.
3. We definitely want to preserve comments and variable names as much as possible. People put useful information in these things; if we erase them users will distrust any change Resyntax suggests in the future.
4. Preserving failure behavior could be valuable, but it might not be. It's hard to say in the abstract. Communicating caveats to the user through #4 could be one way to address this.

**Comment by Metaxal** [comment]
Oh, here's possibly a good way to think about it:
When writing such rules, we should always ask: "Is any of the template expressions able to tell (one way or another) if the rule has been applied or not?"

And the related: "Could any of the template expressions behave differently depending on whether the rule has been applied or not?"

**Comment by jackfirth** [comment]
I'm going to close this for now, since I think it's infeasible in the general case and it's a very fuzzy problem. I'll keep this in mind though as we get more experience using Resyntax in the wild.
